In [1]:
import pandas

In [3]:
db = pandas.read_csv('JY.csv')


In [4]:
db

name  hrs  marks
0   anil    2     10
1   ravi    3     20
2    jay    4     30
3  suraj    5     40

In [5]:
type(db)

pandas.core.frame.DataFrame

In [6]:
y = db["marks"]

In [7]:
y

0    10
1    20
2    30
3    40
Name: marks, dtype: int64

In [8]:
type(y)

pandas.core.series.Series

In [9]:
x = db["hrs"]

In [10]:
x

0    2
1    3
2    4
3    5
Name: hrs, dtype: int64

In [11]:
type(x)

pandas.core.series.Series

In [12]:
x = x.values

In [13]:
x

array([2, 3, 4, 5], dtype=int64)

In [14]:
type(x)

numpy.ndarray

In [15]:
x = x.reshape(4,1)

In [16]:
x

array([[2],
       [3],
       [4],
       [5]], dtype=int64)

In [17]:
x.shape

(4, 1)

In [18]:
type(x)

numpy.ndarray

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
mind = LinearRegression()

In [21]:
mind.fit(x, y)

LinearRegression()

In [23]:
mind.predict([[ 4 ]])

array([30.])

In [24]:
mind.coef_

array([10.])

In [26]:
import joblib

In [27]:
joblib.dump(mind , 'JY.csv')

PermissionError: [Errno 13] Permission denied: 'JY.csv'